config/routes.rb
Rails.application.routes.draw do


  
  resources :process_physiques
  resources :process_morales
  resources :physiques
  mount RailsAdmin::Engine => '/banqueopenadmin', as: 'rails_admin'
  resources :morales
  resources :statusclients
  resources :agences
  resources :roles
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :users, only:[:index,:show,:edit,:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/physique.rb
class Physique < ApplicationRecord
	has_many :process_physiques
end

app/controllers/physiques_controller.rb
class PhysiquesController < ApplicationController
  before_action :set_physique, only: [:show, :edit, :update, :destroy]

  # GET /physiques
  # GET /physiques.json
  def index
    if params[:search]
        @physiques = Physique.where(racine_cli: params[:search])
    end

    render json: @physiques
  end

  # GET /physiques/1
  # GET /physiques/1.json
  def show
    render json: @physique
  end

  # GET /physiques/new
  def new
    @physique = Physique.new
  end

  # GET /physiques/1/edit
  def edit
  end

  # POST /physiques
  # POST /physiques.json
  def create
    @physique = Physique.new(physique_params)

    respond_to do |format|
      if @physique.save
        format.html { redirect_to @physique, notice: 'Physique was successfully created.' }
        format.json { render :show, status: :created, location: @physique }
      else
        format.html { render :new }
        format.json { render json: @physique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physiques/1
  # PATCH/PUT /physiques/1.json
  def update
    #respond_to do |format|
      if @physique.update(physique_params)
        #format.html { redirect_to @physique, notice: 'Physique was successfully updated.' }
        #format.json { render :show, status: :ok, location: @physique }
        render json: @physique
      else
        #format.html { render :edit }
        #format.json { render json: @physique.errors, status: :unprocessable_entity }
        render json: @physique.errors
      end
    #end
  end

  # DELETE /physiques/1
  # DELETE /physiques/1.json
  def destroy
    @physique.destroy
    # respond_to do |format|
    #   format.html { redirect_to physiques_url, notice: 'Physique was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physique
      @physique = Physique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physique_params
      params.require(:physique).permit(:racine_cli, :etat_civil, :code_sexe, :situation_matrimonial, :juridique, :qualite, :profession, :nbre_enfants, :prenoms, :marital_nom, :marital_prenom, :nom_de_la_mere, :prenoms_du_mere, :nom_du_pere, :prenoms_du_pere, :piece, :numero, :iso_pays, :dep_delivre_ci, :delivree, :validite, :pays_nationalite, :naissance, :iso_pays_naissance, :commune, :pays_de_residence, :dep_de_residence, :adresse_residence, :ville_residence, :pays, :portable, :courr, :diplome_obtenu, :salaire_net, :date_embauche, :date_depart_retraite, :employeur, :situation_residentielle, :nature_contrat, :adehesion_bic, :adres_nature, :pays_adres, :code_courier_adresse, :commune, :pays_pour_etranger, :langue, :devise_de_reference, :pays_de_nationalite, :pays_de_residence, :pays_de_resid_fiscal, :categorie_juridique, :code_ape, :option_fiscal, :assujetissement_tva, :credit_immed_chq_effets, :grp_confid_client, :affichage_sld_si_cond, :rleve_mois_sans_mvts, :classification, :surveillance, :secret, :succession, :instruction, :date_ouverture, :expl_resp, :agence, :autorisation_chequier, :interdiction_chequier, :num_cart_resid, :iub_cip, :secteur_institutionnel, :titre_string, :precision_date_de_naissance, :nature_clientele, :secteur_activite, :mand, :donne_par, :pouvoir, :date_effet, :date_echance, :email, :cotation, :titre, :satut_residentiel, :fatca, :aml)
    end
end

app/helpers/physiques_helper.rb
module PhysiquesHelper
end

app/views/physiques/_form.html.erb
<%= simple_form_for(@physique) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :racine_cli %>
    <%= f.input :etat_civil %>
    <%= f.input :code_sexe %>
    <%= f.input :situation_matrimonial %>
    <%= f.input :juridique %>
    <%= f.input :qualite %>
    <%= f.input :profession %>
    <%= f.input :nbre_enfants %>
    <%= f.input :prenoms %>
    <%= f.input :marital_nom %>
    <%= f.input :marital_prenom %>
    <%= f.input :nom_de_la_mere %>
    <%= f.input :prenoms_du_mere %>
    <%= f.input :nom_du_pere %>
    <%= f.input :prenoms_du_pere %>
    <%= f.input :piece %>
    <%= f.input :numero %>
    <%= f.input :iso_pays %>
    <%= f.input :dep_delivre_ci %>
    <%= f.input :delivree %>
    <%= f.input :validite %>
    <%= f.input :pays_nationalite %>
    <%= f.input :naissance %>
    <%= f.input :iso_pays_naissance %>
    <%= f.input :commune %>
    <%= f.input :pays_de_residence %>
    <%= f.input :dep_de_residence %>
    <%= f.input :adresse_residence %>
    <%= f.input :ville_residence %>
    <%= f.input :pays %>
    <%= f.input :portable %>
    <%= f.input :courr %>
    <%= f.input :diplome_obtenu %>
    <%= f.input :salaire_net %>
    <%= f.input :date_embauche %>
    <%= f.input :date_depart_retraite %>
    <%= f.input :employeur %>
    <%= f.input :situation_residentielle %>
    <%= f.input :nature_contrat %>
    <%= f.input :adehesion_bic %>
    <%= f.input :adres_nature %>
    <%= f.input :pays_adres %>
    <%= f.input :code_courier_adresse %>
    <%= f.input :commune %>
    <%= f.input :pays_pour_etranger %>
    <%= f.input :langue %>
    <%= f.input :devise_de_reference %>
    <%= f.input :pays_de_nationalite %>
    <%= f.input :pays_de_residence %>
    <%= f.input :pays_de_resid_fiscal %>
    <%= f.input :categorie_juridique %>
    <%= f.input :code_ape %>
    <%= f.input :option_fiscal %>
    <%= f.input :assujetissement_tva %>
    <%= f.input :credit_immed_chq_effets %>
    <%= f.input :grp_confid_client %>
    <%= f.input :affichage_sld_si_cond %>
    <%= f.input :rleve_mois_sans_mvts %>
    <%= f.input :classification %>
    <%= f.input :surveillance %>
    <%= f.input :secret %>
    <%= f.input :succession %>
    <%= f.input :instruction %>
    <%= f.input :date_ouverture %>
    <%= f.input :expl_resp %>
    <%= f.input :agence %>
    <%= f.input :autorisation_chequier %>
    <%= f.input :interdiction_chequier %>
    <%= f.input :num_cart_resid %>
    <%= f.input :iub_cip %>
    <%= f.input :secteur_institutionnel %>
    <%= f.input :titre_string %>
    <%= f.input :precision_date_de_naissance %>
    <%= f.input :nature_clientele %>
    <%= f.input :secteur_activite %>
    <%= f.input :mand %>
    <%= f.input :donne_par %>
    <%= f.input :pouvoir %>
    <%= f.input :date_effet %>
    <%= f.input :date_echance %>
    <%= f.input :email %>
    <%= f.input :cotation %>
    <%= f.input :titre %>
    <%= f.input :satut_residentiel %>
    <%= f.input :fatca %>
    <%= f.input :aml %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/physiques/edit.html.erb
<h1>Editing Physique</h1>

<%= render 'form', physique: @physique %>

<%= link_to 'Show', @physique %> |
<%= link_to 'Back', physiques_path %>

app/views/physiques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physiques</h1>

<table>
  <thead>
    <tr>
      <th>Racine cli</th>
      <th>Etat civil</th>
      <th>Code sexe</th>
      <th>Situation matrimonial</th>
      <th>Juridique</th>
      <th>Qualite</th>
      <th>Profession</th>
      <th>Nbre enfants</th>
      <th>Prenoms</th>
      <th>Marital nom</th>
      <th>Marital prenom</th>
      <th>Nom de la mere</th>
      <th>Prenoms du mere</th>
      <th>Nom du pere</th>
      <th>Prenoms du pere</th>
      <th>Piece</th>
      <th>Numero</th>
      <th>Iso pays</th>
      <th>Dep delivre ci</th>
      <th>Delivree</th>
      <th>Validite</th>
      <th>Pays nationalite</th>
      <th>Naissance</th>
      <th>Iso pays naissance</th>
      <th>Commune</th>
      <th>Pays de residence</th>
      <th>Dep de residence</th>
      <th>Adresse residence</th>
      <th>Ville residence</th>
      <th>Pays</th>
      <th>Portable</th>
      <th>Courr</th>
      <th>Diplome obtenu</th>
      <th>Salaire net</th>
      <th>Date embauche</th>
      <th>Date depart retraite</th>
      <th>Employeur</th>
      <th>Situation residentielle</th>
      <th>Nature contrat</th>
      <th>Adehesion bic</th>
      <th>Adres nature</th>
      <th>Pays adres</th>
      <th>Code courier adresse</th>
      <th>Commune</th>
      <th>Pays pour etranger</th>
      <th>Langue</th>
      <th>Devise de reference</th>
      <th>Pays de nationalite</th>
      <th>Pays de residence</th>
      <th>Pays de resid fiscal</th>
      <th>Categorie juridique</th>
      <th>Code ape</th>
      <th>Option fiscal</th>
      <th>Assujetissement tva</th>
      <th>Credit immed chq effets</th>
      <th>Grp confid client</th>
      <th>Affichage sld si cond</th>
      <th>Rleve mois sans mvts</th>
      <th>Classification</th>
      <th>Surveillance</th>
      <th>Secret</th>
      <th>Succession</th>
      <th>Instruction</th>
      <th>Date ouverture</th>
      <th>Expl resp</th>
      <th>Agence</th>
      <th>Autorisation chequier</th>
      <th>Interdiction chequier</th>
      <th>Num cart resid</th>
      <th>Iub cip</th>
      <th>Secteur institutionnel</th>
      <th>Titre string</th>
      <th>Precision date de naissance</th>
      <th>Nature clientele</th>
      <th>Secteur activite</th>
      <th>Mand</th>
      <th>Donne par</th>
      <th>Pouvoir</th>
      <th>Date effet</th>
      <th>Date echance</th>
      <th>Email</th>
      <th>Cotation</th>
      <th>Titre</th>
      <th>Satut residentiel</th>
      <th>Fatca</th>
      <th>Aml</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physiques.each do |physique| %>
      <tr>
        <td><%= physique.racine_cli %></td>
        <td><%= physique.etat_civil %></td>
        <td><%= physique.code_sexe %></td>
        <td><%= physique.situation_matrimonial %></td>
        <td><%= physique.juridique %></td>
        <td><%= physique.qualite %></td>
        <td><%= physique.profession %></td>
        <td><%= physique.nbre_enfants %></td>
        <td><%= physique.prenoms %></td>
        <td><%= physique.marital_nom %></td>
        <td><%= physique.marital_prenom %></td>
        <td><%= physique.nom_de_la_mere %></td>
        <td><%= physique.prenoms_du_mere %></td>
        <td><%= physique.nom_du_pere %></td>
        <td><%= physique.prenoms_du_pere %></td>
        <td><%= physique.piece %></td>
        <td><%= physique.numero %></td>
        <td><%= physique.iso_pays %></td>
        <td><%= physique.dep_delivre_ci %></td>
        <td><%= physique.delivree %></td>
        <td><%= physique.validite %></td>
        <td><%= physique.pays_nationalite %></td>
        <td><%= physique.naissance %></td>
        <td><%= physique.iso_pays_naissance %></td>
        <td><%= physique.commune %></td>
        <td><%= physique.pays_de_residence %></td>
        <td><%= physique.dep_de_residence %></td>
        <td><%= physique.adresse_residence %></td>
        <td><%= physique.ville_residence %></td>
        <td><%= physique.pays %></td>
        <td><%= physique.portable %></td>
        <td><%= physique.courr %></td>
        <td><%= physique.diplome_obtenu %></td>
        <td><%= physique.salaire_net %></td>
        <td><%= physique.date_embauche %></td>
        <td><%= physique.date_depart_retraite %></td>
        <td><%= physique.employeur %></td>
        <td><%= physique.situation_residentielle %></td>
        <td><%= physique.nature_contrat %></td>
        <td><%= physique.adehesion_bic %></td>
        <td><%= physique.adres_nature %></td>
        <td><%= physique.pays_adres %></td>
        <td><%= physique.code_courier_adresse %></td>
        <td><%= physique.commune %></td>
        <td><%= physique.pays_pour_etranger %></td>
        <td><%= physique.langue %></td>
        <td><%= physique.devise_de_reference %></td>
        <td><%= physique.pays_de_nationalite %></td>
        <td><%= physique.pays_de_residence %></td>
        <td><%= physique.pays_de_resid_fiscal %></td>
        <td><%= physique.categorie_juridique %></td>
        <td><%= physique.code_ape %></td>
        <td><%= physique.option_fiscal %></td>
        <td><%= physique.assujetissement_tva %></td>
        <td><%= physique.credit_immed_chq_effets %></td>
        <td><%= physique.grp_confid_client %></td>
        <td><%= physique.affichage_sld_si_cond %></td>
        <td><%= physique.rleve_mois_sans_mvts %></td>
        <td><%= physique.classification %></td>
        <td><%= physique.surveillance %></td>
        <td><%= physique.secret %></td>
        <td><%= physique.succession %></td>
        <td><%= physique.instruction %></td>
        <td><%= physique.date_ouverture %></td>
        <td><%= physique.expl_resp %></td>
        <td><%= physique.agence %></td>
        <td><%= physique.autorisation_chequier %></td>
        <td><%= physique.interdiction_chequier %></td>
        <td><%= physique.num_cart_resid %></td>
        <td><%= physique.iub_cip %></td>
        <td><%= physique.secteur_institutionnel %></td>
        <td><%= physique.titre_string %></td>
        <td><%= physique.precision_date_de_naissance %></td>
        <td><%= physique.nature_clientele %></td>
        <td><%= physique.secteur_activite %></td>
        <td><%= physique.mand %></td>
        <td><%= physique.donne_par %></td>
        <td><%= physique.pouvoir %></td>
        <td><%= physique.date_effet %></td>
        <td><%= physique.date_echance %></td>
        <td><%= physique.email %></td>
        <td><%= physique.cotation %></td>
        <td><%= physique.titre %></td>
        <td><%= physique.satut_residentiel %></td>
        <td><%= physique.fatca %></td>
        <td><%= physique.aml %></td>
        <td><%= link_to 'Show', physique %></td>
        <td><%= link_to 'Edit', edit_physique_path(physique) %></td>
        <td><%= link_to 'Destroy', physique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physique', new_physique_path %>

app/views/physiques/new.html.erb
<h1>New Physique</h1>

<%= render 'form', physique: @physique %>

<%= link_to 'Back', physiques_path %>

app/views/physiques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Racine cli:</strong>
  <%= @physique.racine_cli %>
</p>

<p>
  <strong>Etat civil:</strong>
  <%= @physique.etat_civil %>
</p>

<p>
  <strong>Code sexe:</strong>
  <%= @physique.code_sexe %>
</p>

<p>
  <strong>Situation matrimonial:</strong>
  <%= @physique.situation_matrimonial %>
</p>

<p>
  <strong>Juridique:</strong>
  <%= @physique.juridique %>
</p>

<p>
  <strong>Qualite:</strong>
  <%= @physique.qualite %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @physique.profession %>
</p>

<p>
  <strong>Nbre enfants:</strong>
  <%= @physique.nbre_enfants %>
</p>

<p>
  <strong>Prenoms:</strong>
  <%= @physique.prenoms %>
</p>

<p>
  <strong>Marital nom:</strong>
  <%= @physique.marital_nom %>
</p>

<p>
  <strong>Marital prenom:</strong>
  <%= @physique.marital_prenom %>
</p>

<p>
  <strong>Nom de la mere:</strong>
  <%= @physique.nom_de_la_mere %>
</p>

<p>
  <strong>Prenoms du mere:</strong>
  <%= @physique.prenoms_du_mere %>
</p>

<p>
  <strong>Nom du pere:</strong>
  <%= @physique.nom_du_pere %>
</p>

<p>
  <strong>Prenoms du pere:</strong>
  <%= @physique.prenoms_du_pere %>
</p>

<p>
  <strong>Piece:</strong>
  <%= @physique.piece %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @physique.numero %>
</p>

<p>
  <strong>Iso pays:</strong>
  <%= @physique.iso_pays %>
</p>

<p>
  <strong>Dep delivre ci:</strong>
  <%= @physique.dep_delivre_ci %>
</p>

<p>
  <strong>Delivree:</strong>
  <%= @physique.delivree %>
</p>

<p>
  <strong>Validite:</strong>
  <%= @physique.validite %>
</p>

<p>
  <strong>Pays nationalite:</strong>
  <%= @physique.pays_nationalite %>
</p>

<p>
  <strong>Naissance:</strong>
  <%= @physique.naissance %>
</p>

<p>
  <strong>Iso pays naissance:</strong>
  <%= @physique.iso_pays_naissance %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @physique.commune %>
</p>

<p>
  <strong>Pays de residence:</strong>
  <%= @physique.pays_de_residence %>
</p>

<p>
  <strong>Dep de residence:</strong>
  <%= @physique.dep_de_residence %>
</p>

<p>
  <strong>Adresse residence:</strong>
  <%= @physique.adresse_residence %>
</p>

<p>
  <strong>Ville residence:</strong>
  <%= @physique.ville_residence %>
</p>

<p>
  <strong>Pays:</strong>
  <%= @physique.pays %>
</p>

<p>
  <strong>Portable:</strong>
  <%= @physique.portable %>
</p>

<p>
  <strong>Courr:</strong>
  <%= @physique.courr %>
</p>

<p>
  <strong>Diplome obtenu:</strong>
  <%= @physique.diplome_obtenu %>
</p>

<p>
  <strong>Salaire net:</strong>
  <%= @physique.salaire_net %>
</p>

<p>
  <strong>Date embauche:</strong>
  <%= @physique.date_embauche %>
</p>

<p>
  <strong>Date depart retraite:</strong>
  <%= @physique.date_depart_retraite %>
</p>

<p>
  <strong>Employeur:</strong>
  <%= @physique.employeur %>
</p>

<p>
  <strong>Situation residentielle:</strong>
  <%= @physique.situation_residentielle %>
</p>

<p>
  <strong>Nature contrat:</strong>
  <%= @physique.nature_contrat %>
</p>

<p>
  <strong>Adehesion bic:</strong>
  <%= @physique.adehesion_bic %>
</p>

<p>
  <strong>Adres nature:</strong>
  <%= @physique.adres_nature %>
</p>

<p>
  <strong>Pays adres:</strong>
  <%= @physique.pays_adres %>
</p>

<p>
  <strong>Code courier adresse:</strong>
  <%= @physique.code_courier_adresse %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @physique.commune %>
</p>

<p>
  <strong>Pays pour etranger:</strong>
  <%= @physique.pays_pour_etranger %>
</p>

<p>
  <strong>Langue:</strong>
  <%= @physique.langue %>
</p>

<p>
  <strong>Devise de reference:</strong>
  <%= @physique.devise_de_reference %>
</p>

<p>
  <strong>Pays de nationalite:</strong>
  <%= @physique.pays_de_nationalite %>
</p>

<p>
  <strong>Pays de residence:</strong>
  <%= @physique.pays_de_residence %>
</p>

<p>
  <strong>Pays de resid fiscal:</strong>
  <%= @physique.pays_de_resid_fiscal %>
</p>

<p>
  <strong>Categorie juridique:</strong>
  <%= @physique.categorie_juridique %>
</p>

<p>
  <strong>Code ape:</strong>
  <%= @physique.code_ape %>
</p>

<p>
  <strong>Option fiscal:</strong>
  <%= @physique.option_fiscal %>
</p>

<p>
  <strong>Assujetissement tva:</strong>
  <%= @physique.assujetissement_tva %>
</p>

<p>
  <strong>Credit immed chq effets:</strong>
  <%= @physique.credit_immed_chq_effets %>
</p>

<p>
  <strong>Grp confid client:</strong>
  <%= @physique.grp_confid_client %>
</p>

<p>
  <strong>Affichage sld si cond:</strong>
  <%= @physique.affichage_sld_si_cond %>
</p>

<p>
  <strong>Rleve mois sans mvts:</strong>
  <%= @physique.rleve_mois_sans_mvts %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @physique.classification %>
</p>

<p>
  <strong>Surveillance:</strong>
  <%= @physique.surveillance %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @physique.secret %>
</p>

<p>
  <strong>Succession:</strong>
  <%= @physique.succession %>
</p>

<p>
  <strong>Instruction:</strong>
  <%= @physique.instruction %>
</p>

<p>
  <strong>Date ouverture:</strong>
  <%= @physique.date_ouverture %>
</p>

<p>
  <strong>Expl resp:</strong>
  <%= @physique.expl_resp %>
</p>

<p>
  <strong>Agence:</strong>
  <%= @physique.agence %>
</p>

<p>
  <strong>Autorisation chequier:</strong>
  <%= @physique.autorisation_chequier %>
</p>

<p>
  <strong>Interdiction chequier:</strong>
  <%= @physique.interdiction_chequier %>
</p>

<p>
  <strong>Num cart resid:</strong>
  <%= @physique.num_cart_resid %>
</p>

<p>
  <strong>Iub cip:</strong>
  <%= @physique.iub_cip %>
</p>

<p>
  <strong>Secteur institutionnel:</strong>
  <%= @physique.secteur_institutionnel %>
</p>

<p>
  <strong>Titre string:</strong>
  <%= @physique.titre_string %>
</p>

<p>
  <strong>Precision date de naissance:</strong>
  <%= @physique.precision_date_de_naissance %>
</p>

<p>
  <strong>Nature clientele:</strong>
  <%= @physique.nature_clientele %>
</p>

<p>
  <strong>Secteur activite:</strong>
  <%= @physique.secteur_activite %>
</p>

<p>
  <strong>Mand:</strong>
  <%= @physique.mand %>
</p>

<p>
  <strong>Donne par:</strong>
  <%= @physique.donne_par %>
</p>

<p>
  <strong>Pouvoir:</strong>
  <%= @physique.pouvoir %>
</p>

<p>
  <strong>Date effet:</strong>
  <%= @physique.date_effet %>
</p>

<p>
  <strong>Date echance:</strong>
  <%= @physique.date_echance %>
</p>

<p>
  <strong>Email:</strong>
  <%= @physique.email %>
</p>

<p>
  <strong>Cotation:</strong>
  <%= @physique.cotation %>
</p>

<p>
  <strong>Titre:</strong>
  <%= @physique.titre %>
</p>

<p>
  <strong>Satut residentiel:</strong>
  <%= @physique.satut_residentiel %>
</p>

<p>
  <strong>Fatca:</strong>
  <%= @physique.fatca %>
</p>

<p>
  <strong>Aml:</strong>
  <%= @physique.aml %>
</p>

<%= link_to 'Edit', edit_physique_path(@physique) %> |
<%= link_to 'Back', physiques_path %>