config/routes.rb
Rails.application.routes.draw do


  
  resources :process_physiques
  resources :process_morales
  resources :physiques
  mount RailsAdmin::Engine => '/banqueopenadmin', as: 'rails_admin'
  resources :morales
  resources :statusclients
  resources :agences
  resources :roles
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :users, only:[:index,:show,:edit,:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/process_morale.rb
class ProcessMorale < ApplicationRecord
  belongs_to :user
  belongs_to :statusclient
  belongs_to :morale

  def as_json(options={})
      super(
          :include =>{
          	:only => [:created_at],
            :user => {:only => [:name,:nickname,:email]},
            :statusclient => {:only => [:status]},
            :morale => {:only => [:racine_cli]}
          }
        )
    end
end

app/controllers/process_morales_controller.rb
class ProcessMoralesController < ApplicationController
  before_action :set_process_morale, only: [:show, :edit, :update, :destroy]

  # GET /process_morales
  # GET /process_morales.json
  def index
    @process_morales = ProcessMorale.all

    render json: @process_morales
  end

  # GET /process_morales/1
  # GET /process_morales/1.json
  def show
    render json: @process_morale
  end

  # GET /process_morales/new
  def new
    @process_morale = ProcessMorale.new
  end

  # GET /process_morales/1/edit
  def edit
  end

  # POST /process_morales
  # POST /process_morales.json
  def create
    @process_morale = ProcessMorale.new(process_morale_params)

    respond_to do |format|
      if @process_morale.save
        format.html { redirect_to @process_morale, notice: 'Process morale was successfully created.' }
        format.json { render :show, status: :created, location: @process_morale }
      else
        format.html { render :new }
        format.json { render json: @process_morale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /process_morales/1
  # PATCH/PUT /process_morales/1.json
  def update
    # respond_to do |format|
      if @process_morale.update(process_morale_params)
        # format.html { redirect_to @process_morale, notice: 'Process morale was successfully updated.' }
        # format.json { render :show, status: :ok, location: @process_morale }
        render json: @process_morale
      else
        # format.html { render :edit }
        # format.json { render json: @process_morale.errors, status: :unprocessable_entity }
        render json: @process_morale
      end
    # end
  end

  # DELETE /process_morales/1
  # DELETE /process_morales/1.json
  def destroy
    @process_morale.destroy
    # respond_to do |format|
    #   format.html { redirect_to process_morales_url, notice: 'Process morale was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_process_morale
      @process_morale = ProcessMorale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def process_morale_params
      params.require(:process_morale).permit(:user_id, :statusclient_id, :morale_id)
    end
end

app/helpers/process_morales_helper.rb
module ProcessMoralesHelper
end

app/views/process_morales/_form.html.erb
<%= simple_form_for(@process_morale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :statusclient %>
    <%= f.association :morale %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/process_morales/edit.html.erb
<h1>Editing Process Morale</h1>

<%= render 'form', process_morale: @process_morale %>

<%= link_to 'Show', @process_morale %> |
<%= link_to 'Back', process_morales_path %>

app/views/process_morales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Process Morales</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Statusclient</th>
      <th>Morale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @process_morales.each do |process_morale| %>
      <tr>
        <td><%= process_morale.user %></td>
        <td><%= process_morale.statusclient %></td>
        <td><%= process_morale.morale %></td>
        <td><%= link_to 'Show', process_morale %></td>
        <td><%= link_to 'Edit', edit_process_morale_path(process_morale) %></td>
        <td><%= link_to 'Destroy', process_morale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Process Morale', new_process_morale_path %>

app/views/process_morales/new.html.erb
<h1>New Process Morale</h1>

<%= render 'form', process_morale: @process_morale %>

<%= link_to 'Back', process_morales_path %>

app/views/process_morales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @process_morale.user %>
</p>

<p>
  <strong>Statusclient:</strong>
  <%= @process_morale.statusclient %>
</p>

<p>
  <strong>Morale:</strong>
  <%= @process_morale.morale %>
</p>

<%= link_to 'Edit', edit_process_morale_path(@process_morale) %> |
<%= link_to 'Back', process_morales_path %>