config/routes.rb
Rails.application.routes.draw do


  
  resources :process_physiques
  resources :process_morales
  resources :physiques
  mount RailsAdmin::Engine => '/banqueopenadmin', as: 'rails_admin'
  resources :morales
  resources :statusclients
  resources :agences
  resources :roles
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :users, only:[:index,:show,:edit,:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agence.rb
class Agence < ApplicationRecord
	has_many :users
end

app/controllers/agences_controller.rb
class AgencesController < ApplicationController
  before_action :set_agence, only: [:show, :edit, :update, :destroy]

  # GET /agences
  # GET /agences.json
  def index
    @agences = Agence.all

    render json: @agences
  end

  # GET /agences/1
  # GET /agences/1.json
  def show
    render json: @agence
  end

  # GET /agences/new
  def new
    @agence = Agence.new
  end

  # GET /agences/1/edit
  def edit
  end

  # POST /agences
  # POST /agences.json
  def create
    @agence = Agence.new(agence_params)

    respond_to do |format|
      if @agence.save
        format.html { redirect_to @agence, notice: 'Agence was successfully created.' }
        format.json { render :show, status: :created, location: @agence }
      else
        format.html { render :new }
        format.json { render json: @agence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agences/1
  # PATCH/PUT /agences/1.json
  def update
    #respond_to do |format|
      if @agence.update(agence_params)
        #format.html { redirect_to @agence, notice: 'Agence was successfully updated.' }
        #format.json { render :show, status: :ok, location: @agence }
        render json: @agence
      else
        #format.html { render :edit }
        #format.json { render json: @agence.errors, status: :unprocessable_entity }
        render json: @agence.errors
      end
    #end
  end

  # DELETE /agences/1
  # DELETE /agences/1.json
  def destroy
    @agence.destroy
    # respond_to do |format|
    #   format.html { redirect_to agences_url, notice: 'Agence was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agence
      @agence = Agence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agence_params
      params.require(:agence).permit(:code, :nom)
    end
end

app/helpers/agences_helper.rb
module AgencesHelper
end

app/views/agences/_form.html.erb
<%= simple_form_for(@agence) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :nom %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/agences/edit.html.erb
<h1>Editing Agence</h1>

<%= render 'form', agence: @agence %>

<%= link_to 'Show', @agence %> |
<%= link_to 'Back', agences_path %>

app/views/agences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agences</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agences.each do |agence| %>
      <tr>
        <td><%= agence.code %></td>
        <td><%= agence.nom %></td>
        <td><%= link_to 'Show', agence %></td>
        <td><%= link_to 'Edit', edit_agence_path(agence) %></td>
        <td><%= link_to 'Destroy', agence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agence', new_agence_path %>

app/views/agences/new.html.erb
<h1>New Agence</h1>

<%= render 'form', agence: @agence %>

<%= link_to 'Back', agences_path %>

app/views/agences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @agence.code %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @agence.nom %>
</p>

<%= link_to 'Edit', edit_agence_path(@agence) %> |
<%= link_to 'Back', agences_path %>