config/routes.rb
Rails.application.routes.draw do


  
  resources :process_physiques
  resources :process_morales
  resources :physiques
  mount RailsAdmin::Engine => '/banqueopenadmin', as: 'rails_admin'
  resources :morales
  resources :statusclients
  resources :agences
  resources :roles
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :users, only:[:index,:show,:edit,:new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/morale.rb
class Morale < ApplicationRecord
	has_many :process_morales
end

app/controllers/morales_controller.rb
class MoralesController < ApplicationController
  before_action :set_morale, only: [:show, :edit, :update, :destroy]

  # GET /morales
  # GET /morales.json
  def index
    if params[:search]
        @morales = Morale.where(racine_cli: params[:search])
    end

    render json: @morales
      

  end

  # GET /morales/1
  # GET /morales/1.json
  def show
    render json: @morale
  end

  # GET /morales/new
  def new
    @morale = Morale.new
  end

  # GET /morales/1/edit
  def edit
    
  end

  # POST /morales
  # POST /morales.json
  def create
    @morale = Morale.new(morale_params)

    respond_to do |format|
      if @morale.save
        format.html { redirect_to @morale, notice: 'Morale was successfully created.' }
        format.json { render :show, status: :created, location: @morale }
      else
        format.html { render :new }
        format.json { render json: @morale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morales/1
  # PATCH/PUT /morales/1.json
  def update
    #respond_to do |format|
      if @morale.update(morale_params)
        #format.html { redirect_to @morale, notice: 'Morale was successfully updated.' }
        #format.json { render :show, status: :ok, location: @morale }
          render json: @morale
      else
        #format.html { render :edit }
        #format.json { render json: @morale.errors, status: :unprocessable_entity }
         render json: @morale.errors
      end
    #end
  end

  # DELETE /morales/1
  # DELETE /morales/1.json
  def destroy
    @morale.destroy
    respond_to do |format|
      format.html { redirect_to morales_url, notice: 'Morale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morale
      @morale = Morale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def morale_params
      params.require(:morale).permit(:racine_cli, :nom_jur, :date_ouv, :obj_sco, :rcs, :categ_jur, :forme, :pays_crea, :pays_exploit, :code_ape, :lieu, :capital, :ca_social_ht, :adresse_nom, :adresse_comp_nom, :adresse, :ville, :pays, :code_postal, :fixe, :email, :langue, :courr, :prs, :ident, :nom_signataire, :qualite_fonction, :pouvoir, :type_signataire, :dateffet, :date_echance, :mont_max, :date_decision, :bic, :langue, :devise_de_reference, :pays_de_nationalite, :pays_de_residence, :pays_de_residence_fiscal, :public_privee, :option_fiscal, :assujetissement_tva, :actionnaires, :consolide, :apparente, :participation_client_dans_banque, :participatio_banque_dans_client, :autorisation_chequier, :interdiction_chequier, :credit_immed_chq_effets, :contrat_gestion, :calcul_de_performance, :grp_confid_client, :affichage_sld_si_cond, :releves_mois_mvts, :releves_mois_sans_mvts, :classification, :surveillance, :secret, :sucession, :instruction_tel, :date_ouverture, :expl_resp, :agence, :notation_type, :date, :groupe_de_clients_lies, :iub_cip, :nature_clientele, :groupe_activite, :secteur_institutionnel, :forme_juridique, :siren, :ninea, :agec, :secteur_activite, :effect, :sres, :fax, :num_ifu, :segmentation, :fatca, :aml)
    end
end

app/helpers/morales_helper.rb
module MoralesHelper
end

app/views/morales/_form.html.erb
<%= simple_form_for(@morale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :racine_cli %>
    <%= f.input :nom_jur %>
    <%= f.input :date_ouv %>
    <%= f.input :obj_sco %>
    <%= f.input :rcs %>
    <%= f.input :categ_jur %>
    <%= f.input :forme %>
    <%= f.input :pays_crea %>
    <%= f.input :pays_exploit %>
    <%= f.input :code_ape %>
    <%= f.input :lieu %>
    <%= f.input :capital %>
    <%= f.input :ca_social_ht %>
    <%= f.input :adresse_nom %>
    <%= f.input :adresse_comp_nom %>
    <%= f.input :adresse %>
    <%= f.input :ville %>
    <%= f.input :pays %>
    <%= f.input :code_postal %>
    <%= f.input :fixe %>
    <%= f.input :email %>
    <%= f.input :langue %>
    <%= f.input :courr %>
    <%= f.input :prs %>
    <%= f.input :ident %>
    <%= f.input :nom_signataire %>
    <%= f.input :qualite_fonction %>
    <%= f.input :pouvoir %>
    <%= f.input :type_signataire %>
    <%= f.input :dateffet %>
    <%= f.input :date_echance %>
    <%= f.input :mont_max %>
    <%= f.input :date_decision %>
    <%= f.input :bic %>
    <%= f.input :langue %>
    <%= f.input :devise_de_reference %>
    <%= f.input :pays_de_nationalite %>
    <%= f.input :pays_de_residence %>
    <%= f.input :pays_de_residence_fiscal %>
    <%= f.input :public_privee %>
    <%= f.input :option_fiscal %>
    <%= f.input :assujetissement_tva %>
    <%= f.input :actionnaires %>
    <%= f.input :consolide %>
    <%= f.input :apparente %>
    <%= f.input :participation_client_dans_banque %>
    <%= f.input :participatio_banque_dans_client %>
    <%= f.input :autorisation_chequier %>
    <%= f.input :interdiction_chequier %>
    <%= f.input :credit_immed_chq_effets %>
    <%= f.input :contrat_gestion %>
    <%= f.input :calcul_de_performance %>
    <%= f.input :grp_confid_client %>
    <%= f.input :affichage_sld_si_cond %>
    <%= f.input :releves_mois_mvts %>
    <%= f.input :releves_mois_sans_mvts %>
    <%= f.input :classification %>
    <%= f.input :surveillance %>
    <%= f.input :secret %>
    <%= f.input :sucession %>
    <%= f.input :instruction_tel %>
    <%= f.input :date_ouverture %>
    <%= f.input :expl_resp %>
    <%= f.input :agence %>
    <%= f.input :notation_type %>
    <%= f.input :date %>
    <%= f.input :groupe_de_clients_lies %>
    <%= f.input :iub_cip %>
    <%= f.input :nature_clientele %>
    <%= f.input :groupe_activite %>
    <%= f.input :secteur_institutionnel %>
    <%= f.input :forme_juridique %>
    <%= f.input :siren %>
    <%= f.input :ninea %>
    <%= f.input :agec %>
    <%= f.input :secteur_activite %>
    <%= f.input :effect %>
    <%= f.input :sres %>
    <%= f.input :fax %>
    <%= f.input :num_ifu %>
    <%= f.input :segmentation %>
    <%= f.input :fatca %>
    <%= f.input :aml %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/morales/edit.html.erb
<h1>Editing Morale</h1>

<%= render 'form', morale: @morale %>

<%= link_to 'Show', @morale %> |
<%= link_to 'Back', morales_path %>

app/views/morales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Morales</h1>

<table>
  <thead>
    <tr>
      <th>Racine cli</th>
      <th>Nom jur</th>
      <th>Date ouv</th>
      <th>Obj sco</th>
      <th>Rcs</th>
      <th>Categ jur</th>
      <th>Forme</th>
      <th>Pays crea</th>
      <th>Pays exploit</th>
      <th>Code ape</th>
      <th>Lieu</th>
      <th>Capital</th>
      <th>Ca social ht</th>
      <th>Adresse nom</th>
      <th>Adresse comp nom</th>
      <th>Adresse</th>
      <th>Ville</th>
      <th>Pays</th>
      <th>Code postal</th>
      <th>Fixe</th>
      <th>Email</th>
      <th>Langue</th>
      <th>Courr</th>
      <th>Prs</th>
      <th>Ident</th>
      <th>Nom signataire</th>
      <th>Qualite fonction</th>
      <th>Pouvoir</th>
      <th>Type signataire</th>
      <th>Dateffet</th>
      <th>Date echance</th>
      <th>Mont max</th>
      <th>Date decision</th>
      <th>Bic</th>
      <th>Langue</th>
      <th>Devise de reference</th>
      <th>Pays de nationalite</th>
      <th>Pays de residence</th>
      <th>Pays de residence fiscal</th>
      <th>Public privee</th>
      <th>Option fiscal</th>
      <th>Assujetissement tva</th>
      <th>Actionnaires</th>
      <th>Consolide</th>
      <th>Apparente</th>
      <th>Participation client dans banque</th>
      <th>Participatio banque dans client</th>
      <th>Autorisation chequier</th>
      <th>Interdiction chequier</th>
      <th>Credit immed chq effets</th>
      <th>Contrat gestion</th>
      <th>Calcul de performance</th>
      <th>Grp confid client</th>
      <th>Affichage sld si cond</th>
      <th>Releves mois mvts</th>
      <th>Releves mois sans mvts</th>
      <th>Classification</th>
      <th>Surveillance</th>
      <th>Secret</th>
      <th>Sucession</th>
      <th>Instruction tel</th>
      <th>Date ouverture</th>
      <th>Expl resp</th>
      <th>Agence</th>
      <th>Notation type</th>
      <th>Date</th>
      <th>Groupe de clients lies</th>
      <th>Iub cip</th>
      <th>Nature clientele</th>
      <th>Groupe activite</th>
      <th>Secteur institutionnel</th>
      <th>Forme juridique</th>
      <th>Siren</th>
      <th>Ninea</th>
      <th>Agec</th>
      <th>Secteur activite</th>
      <th>Effect</th>
      <th>Sres</th>
      <th>Fax</th>
      <th>Num ifu</th>
      <th>Segmentation</th>
      <th>Fatca</th>
      <th>Aml</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @morales.each do |morale| %>
      <tr>
        <td><%= morale.racine_cli %></td>
        <td><%= morale.nom_jur %></td>
        <td><%= morale.date_ouv %></td>
        <td><%= morale.obj_sco %></td>
        <td><%= morale.rcs %></td>
        <td><%= morale.categ_jur %></td>
        <td><%= morale.forme %></td>
        <td><%= morale.pays_crea %></td>
        <td><%= morale.pays_exploit %></td>
        <td><%= morale.code_ape %></td>
        <td><%= morale.lieu %></td>
        <td><%= morale.capital %></td>
        <td><%= morale.ca_social_ht %></td>
        <td><%= morale.adresse_nom %></td>
        <td><%= morale.adresse_comp_nom %></td>
        <td><%= morale.adresse %></td>
        <td><%= morale.ville %></td>
        <td><%= morale.pays %></td>
        <td><%= morale.code_postal %></td>
        <td><%= morale.fixe %></td>
        <td><%= morale.email %></td>
        <td><%= morale.langue %></td>
        <td><%= morale.courr %></td>
        <td><%= morale.prs %></td>
        <td><%= morale.ident %></td>
        <td><%= morale.nom_signataire %></td>
        <td><%= morale.qualite_fonction %></td>
        <td><%= morale.pouvoir %></td>
        <td><%= morale.type_signataire %></td>
        <td><%= morale.dateffet %></td>
        <td><%= morale.date_echance %></td>
        <td><%= morale.mont_max %></td>
        <td><%= morale.date_decision %></td>
        <td><%= morale.bic %></td>
        <td><%= morale.langue %></td>
        <td><%= morale.devise_de_reference %></td>
        <td><%= morale.pays_de_nationalite %></td>
        <td><%= morale.pays_de_residence %></td>
        <td><%= morale.pays_de_residence_fiscal %></td>
        <td><%= morale.public_privee %></td>
        <td><%= morale.option_fiscal %></td>
        <td><%= morale.assujetissement_tva %></td>
        <td><%= morale.actionnaires %></td>
        <td><%= morale.consolide %></td>
        <td><%= morale.apparente %></td>
        <td><%= morale.participation_client_dans_banque %></td>
        <td><%= morale.participatio_banque_dans_client %></td>
        <td><%= morale.autorisation_chequier %></td>
        <td><%= morale.interdiction_chequier %></td>
        <td><%= morale.credit_immed_chq_effets %></td>
        <td><%= morale.contrat_gestion %></td>
        <td><%= morale.calcul_de_performance %></td>
        <td><%= morale.grp_confid_client %></td>
        <td><%= morale.affichage_sld_si_cond %></td>
        <td><%= morale.releves_mois_mvts %></td>
        <td><%= morale.releves_mois_sans_mvts %></td>
        <td><%= morale.classification %></td>
        <td><%= morale.surveillance %></td>
        <td><%= morale.secret %></td>
        <td><%= morale.sucession %></td>
        <td><%= morale.instruction_tel %></td>
        <td><%= morale.date_ouverture %></td>
        <td><%= morale.expl_resp %></td>
        <td><%= morale.agence %></td>
        <td><%= morale.notation_type %></td>
        <td><%= morale.date %></td>
        <td><%= morale.groupe_de_clients_lies %></td>
        <td><%= morale.iub_cip %></td>
        <td><%= morale.nature_clientele %></td>
        <td><%= morale.groupe_activite %></td>
        <td><%= morale.secteur_institutionnel %></td>
        <td><%= morale.forme_juridique %></td>
        <td><%= morale.siren %></td>
        <td><%= morale.ninea %></td>
        <td><%= morale.agec %></td>
        <td><%= morale.secteur_activite %></td>
        <td><%= morale.effect %></td>
        <td><%= morale.sres %></td>
        <td><%= morale.fax %></td>
        <td><%= morale.num_ifu %></td>
        <td><%= morale.segmentation %></td>
        <td><%= morale.fatca %></td>
        <td><%= morale.aml %></td>
        <td><%= link_to 'Show', morale %></td>
        <td><%= link_to 'Edit', edit_morale_path(morale) %></td>
        <td><%= link_to 'Destroy', morale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Morale', new_morale_path %>

app/views/morales/new.html.erb
<h1>New Morale</h1>

<%= render 'form', morale: @morale %>

<%= link_to 'Back', morales_path %>

app/views/morales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Racine cli:</strong>
  <%= @morale.racine_cli %>
</p>

<p>
  <strong>Nom jur:</strong>
  <%= @morale.nom_jur %>
</p>

<p>
  <strong>Date ouv:</strong>
  <%= @morale.date_ouv %>
</p>

<p>
  <strong>Obj sco:</strong>
  <%= @morale.obj_sco %>
</p>

<p>
  <strong>Rcs:</strong>
  <%= @morale.rcs %>
</p>

<p>
  <strong>Categ jur:</strong>
  <%= @morale.categ_jur %>
</p>

<p>
  <strong>Forme:</strong>
  <%= @morale.forme %>
</p>

<p>
  <strong>Pays crea:</strong>
  <%= @morale.pays_crea %>
</p>

<p>
  <strong>Pays exploit:</strong>
  <%= @morale.pays_exploit %>
</p>

<p>
  <strong>Code ape:</strong>
  <%= @morale.code_ape %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @morale.lieu %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @morale.capital %>
</p>

<p>
  <strong>Ca social ht:</strong>
  <%= @morale.ca_social_ht %>
</p>

<p>
  <strong>Adresse nom:</strong>
  <%= @morale.adresse_nom %>
</p>

<p>
  <strong>Adresse comp nom:</strong>
  <%= @morale.adresse_comp_nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @morale.adresse %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @morale.ville %>
</p>

<p>
  <strong>Pays:</strong>
  <%= @morale.pays %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @morale.code_postal %>
</p>

<p>
  <strong>Fixe:</strong>
  <%= @morale.fixe %>
</p>

<p>
  <strong>Email:</strong>
  <%= @morale.email %>
</p>

<p>
  <strong>Langue:</strong>
  <%= @morale.langue %>
</p>

<p>
  <strong>Courr:</strong>
  <%= @morale.courr %>
</p>

<p>
  <strong>Prs:</strong>
  <%= @morale.prs %>
</p>

<p>
  <strong>Ident:</strong>
  <%= @morale.ident %>
</p>

<p>
  <strong>Nom signataire:</strong>
  <%= @morale.nom_signataire %>
</p>

<p>
  <strong>Qualite fonction:</strong>
  <%= @morale.qualite_fonction %>
</p>

<p>
  <strong>Pouvoir:</strong>
  <%= @morale.pouvoir %>
</p>

<p>
  <strong>Type signataire:</strong>
  <%= @morale.type_signataire %>
</p>

<p>
  <strong>Dateffet:</strong>
  <%= @morale.dateffet %>
</p>

<p>
  <strong>Date echance:</strong>
  <%= @morale.date_echance %>
</p>

<p>
  <strong>Mont max:</strong>
  <%= @morale.mont_max %>
</p>

<p>
  <strong>Date decision:</strong>
  <%= @morale.date_decision %>
</p>

<p>
  <strong>Bic:</strong>
  <%= @morale.bic %>
</p>

<p>
  <strong>Langue:</strong>
  <%= @morale.langue %>
</p>

<p>
  <strong>Devise de reference:</strong>
  <%= @morale.devise_de_reference %>
</p>

<p>
  <strong>Pays de nationalite:</strong>
  <%= @morale.pays_de_nationalite %>
</p>

<p>
  <strong>Pays de residence:</strong>
  <%= @morale.pays_de_residence %>
</p>

<p>
  <strong>Pays de residence fiscal:</strong>
  <%= @morale.pays_de_residence_fiscal %>
</p>

<p>
  <strong>Public privee:</strong>
  <%= @morale.public_privee %>
</p>

<p>
  <strong>Option fiscal:</strong>
  <%= @morale.option_fiscal %>
</p>

<p>
  <strong>Assujetissement tva:</strong>
  <%= @morale.assujetissement_tva %>
</p>

<p>
  <strong>Actionnaires:</strong>
  <%= @morale.actionnaires %>
</p>

<p>
  <strong>Consolide:</strong>
  <%= @morale.consolide %>
</p>

<p>
  <strong>Apparente:</strong>
  <%= @morale.apparente %>
</p>

<p>
  <strong>Participation client dans banque:</strong>
  <%= @morale.participation_client_dans_banque %>
</p>

<p>
  <strong>Participatio banque dans client:</strong>
  <%= @morale.participatio_banque_dans_client %>
</p>

<p>
  <strong>Autorisation chequier:</strong>
  <%= @morale.autorisation_chequier %>
</p>

<p>
  <strong>Interdiction chequier:</strong>
  <%= @morale.interdiction_chequier %>
</p>

<p>
  <strong>Credit immed chq effets:</strong>
  <%= @morale.credit_immed_chq_effets %>
</p>

<p>
  <strong>Contrat gestion:</strong>
  <%= @morale.contrat_gestion %>
</p>

<p>
  <strong>Calcul de performance:</strong>
  <%= @morale.calcul_de_performance %>
</p>

<p>
  <strong>Grp confid client:</strong>
  <%= @morale.grp_confid_client %>
</p>

<p>
  <strong>Affichage sld si cond:</strong>
  <%= @morale.affichage_sld_si_cond %>
</p>

<p>
  <strong>Releves mois mvts:</strong>
  <%= @morale.releves_mois_mvts %>
</p>

<p>
  <strong>Releves mois sans mvts:</strong>
  <%= @morale.releves_mois_sans_mvts %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @morale.classification %>
</p>

<p>
  <strong>Surveillance:</strong>
  <%= @morale.surveillance %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @morale.secret %>
</p>

<p>
  <strong>Sucession:</strong>
  <%= @morale.sucession %>
</p>

<p>
  <strong>Instruction tel:</strong>
  <%= @morale.instruction_tel %>
</p>

<p>
  <strong>Date ouverture:</strong>
  <%= @morale.date_ouverture %>
</p>

<p>
  <strong>Expl resp:</strong>
  <%= @morale.expl_resp %>
</p>

<p>
  <strong>Agence:</strong>
  <%= @morale.agence %>
</p>

<p>
  <strong>Notation type:</strong>
  <%= @morale.notation_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @morale.date %>
</p>

<p>
  <strong>Groupe de clients lies:</strong>
  <%= @morale.groupe_de_clients_lies %>
</p>

<p>
  <strong>Iub cip:</strong>
  <%= @morale.iub_cip %>
</p>

<p>
  <strong>Nature clientele:</strong>
  <%= @morale.nature_clientele %>
</p>

<p>
  <strong>Groupe activite:</strong>
  <%= @morale.groupe_activite %>
</p>

<p>
  <strong>Secteur institutionnel:</strong>
  <%= @morale.secteur_institutionnel %>
</p>

<p>
  <strong>Forme juridique:</strong>
  <%= @morale.forme_juridique %>
</p>

<p>
  <strong>Siren:</strong>
  <%= @morale.siren %>
</p>

<p>
  <strong>Ninea:</strong>
  <%= @morale.ninea %>
</p>

<p>
  <strong>Agec:</strong>
  <%= @morale.agec %>
</p>

<p>
  <strong>Secteur activite:</strong>
  <%= @morale.secteur_activite %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @morale.effect %>
</p>

<p>
  <strong>Sres:</strong>
  <%= @morale.sres %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @morale.fax %>
</p>

<p>
  <strong>Num ifu:</strong>
  <%= @morale.num_ifu %>
</p>

<p>
  <strong>Segmentation:</strong>
  <%= @morale.segmentation %>
</p>

<p>
  <strong>Fatca:</strong>
  <%= @morale.fatca %>
</p>

<p>
  <strong>Aml:</strong>
  <%= @morale.aml %>
</p>

<%= link_to 'Edit', edit_morale_path(@morale) %> |
<%= link_to 'Back', morales_path %>